### PR TITLE
Fleet digiline support

### PR DESCRIPTION
**Pull request by S-S-X**
Some testing required.

### CODE REVIEW

**Comment by S-S-X** [comment]
Issues reported, thanks to @SwissalpS 
https://github.com/S-S-X/jumpdrive/issues/1
https://github.com/S-S-X/jumpdrive/issues/2
https://github.com/S-S-X/jumpdrive/issues/3 marked this as "by design", comments? My opinion: should not be fixed.
https://github.com/S-S-X/jumpdrive/issues/4

**Comment by thomasrudin** [comment]
Are there any issues that can crash the server or break builds?
If not, i don't see a problem with merging, the follow-up issues can be addressed later..

**Comment by S-S-X** [comment]
I've not been able to crash local server with this yet but also I've not tested everything and only with 2 jd fleet.
Also I had only few mods installed: technic, jumpdrive, mesecons, areas/protectors/xp, and hard dependencies of course like pipeworks/moreores etc..

**Comment by SwissalpS** [comment]
Though I have found nothing that will crash the server, I don't feel comfortable with the notion of having to go search for other players fleet portions (because they don't have travelnets on each section).
[S-S-X#1](https://github.com/S-S-X/jumpdrive/issues/1) should be solved first with at least a way to manually stop timer.

**Comment by SwissalpS** [comment]
I have reset all mods to current state of meta repo and checked out S-S-X/jumpdrive digifleet.
(disabled mods like geoip, mapcleaner etc. also my core is still on 5.2.0 2907c0f3)
Made a fleet with two controllers on same channel 'h'.
coords of fc1: 222 124 222
coords of fc2: 223 124 223
luac at 222 125 223

then I run following code in luac:
`local fDLs = digiline_send
local fF = function(t) fDLs('h', t) end
fF({ command = 'set', x = 222, y= 224, z = 222 })
fF({ command = 'show' })`

The fleet does nothing but show the markers.
Now change the show command to jump.
On execution the fleet jumps - so far so good.

Now change y coordinate to 124 and jump command to show
On execution the fleet jumps.

**Comment by S-S-X** [comment]
> However I'm not sure fleet should jump automatically when obstruction is removed 

It definitely should not jump after obstruction is removed unless there's jump command coming in from digiline queue. So this should be fixed somehow, I'll try again with your code @SwissalpS if I can find what causes it.

> fleet portions jump when other portions are obstructed or don't have enough power

It is how it has always worked and one reason why there is "show" / "simulate" command.

It is possible to fix this but good fix will be expensive if fixed properly, actually I would not like to fix that at all but might still work on it if there's some good reasons to support that (i think that noobs lose ships is not good reason, we have good tutorials and they cant be that noob if they can build fleet ship).

**Comment by S-S-X** [comment]
@SwissalpS you have infinite message feedback loop on luac, if there's any limitations on mesecons queue (like ones used on pandorabox) it will keep messages in queue and deliver message later to fleet controllers.

**Comment by S-S-X** [comment]
Last commit fixes issues with async operations by properly marking fleet controller active / inactive.

https://github.com/S-S-X/jumpdrive/issues/2 Probably also fixed but needs some testing

https://github.com/S-S-X/jumpdrive/issues/3 Still open, debatable if this is bug or feature.

**Comment by thomasrudin** [comment]
> (disabled mods like geoip, mapcleaner etc. also my core is still on 5.2.0 2907c0f3)

@SwissalpS **fyi**: the `mapcleaner` is inert by default, the other mods in the `pandorabox-mods` repo should be singleplayer-ready. If not: please open an issue, i'll deal with it...

@S-S-X i see if i get some time tonight to test-drive this :smile:

**Comment by OgelGames** [comment]
@S-S-X I will test it out tomorrow, forgot to do it today :smile:

**Comment by thomasrudin** [comment]
i played with it a little and it worked good so far, no crashes no lost stuff... :+1:

**Comment by SwissalpS** [comment]
I ran some more simple tests could not crash my server and feel that it's OK to merge into master.
Thanks SX :D

**Comment by thomasrudin** [comment]
feel "stable" (in minetest terms :smile:), merging

**Comment by thomasrudin** [comment]
fyi: i fixed a few warnings from luacheck:
https://github.com/mt-mods/jumpdrive/commit/17f57493dd03c25ff61b97d9a422a4b436218f34

Some of the digiline response data was never set...

**Comment by S-S-X** [comment]
> btw: i fixed a few warnings from luacheck:
> [17f5749](https://github.com/mt-mods/jumpdrive/commit/17f57493dd03c25ff61b97d9a422a4b436218f34)
> 
> Some of the digiline response data was never set...

@thomasrudin 

Fixes looks mostly good for me but ones here https://github.com/mt-mods/jumpdrive/commit/17f57493dd03c25ff61b97d9a422a4b436218f34#diff-49886f82456481c325cd37347baba211L278-R301 imo should be fixed either by removing lines completely.

OR

removing line https://github.com/mt-mods/jumpdrive/commit/17f57493dd03c25ff61b97d9a422a4b436218f34#diff-49886f82456481c325cd37347baba211R220 where targetPos is originally set and adding `local` keywords back to https://github.com/mt-mods/jumpdrive/commit/17f57493dd03c25ff61b97d9a422a4b436218f34#diff-49886f82456481c325cd37347baba211L278-R301

**Comment by thomasrudin** [comment]
Done: https://github.com/mt-mods/jumpdrive/commit/46b3752ebecc77e6ff9b98870b56a8a68df972d0

**Pull request merged**
