### PR TITLE
remove tp tube override

### PR DESCRIPTION
**Pull request by BuckarooBanzay**

### CODE REVIEW

**Comment by OgelGames** [comment]
Shouldn't this be removed too? https://github.com/mt-mods/jumpdrive/blob/master/override/teleport_tube.lua

**Comment by BuckarooBanzay** [comment]
> Shouldn't this be removed too? https://github.com/mt-mods/jumpdrive/blob/master/override/teleport_tube.lua

yeah, forgot that :facepalm:

**Comment by S-S-X** [comment]
Does this PR clear this issue too: #75?
Or probably at least parts of it.

**Comment by BuckarooBanzay** [comment]
yes it does :+1:

**Pull request merged**
